"""add exception_emails to form

Revision ID: 78d9dac87570
Revises: d1ca1a1f2b40
Create Date: 2026-01-18 01:32:41.892597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78d9dac87570'
down_revision: Union[str, Sequence[str], None] = 'd1ca1a1f2b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_in_logs_event_type'), table_name='check_in_logs')
    op.drop_index(op.f('ix_check_in_logs_id'), table_name='check_in_logs')
    op.drop_index(op.f('ix_check_in_logs_user_id'), table_name='check_in_logs')
    op.drop_table('check_in_logs')
    op.drop_index(op.f('ix_check_in_id'), table_name='check_in')
    op.drop_index(op.f('ix_check_in_user_id'), table_name='check_in')
    op.drop_table('check_in')
    op.add_column('form', sa.Column('exception_emails', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'exception_emails')
    op.create_table('check_in',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pref_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('check_in_pkey'))
    )
    op.create_index(op.f('ix_check_in_user_id'), 'check_in', ['user_id'], unique=True)
    op.create_index(op.f('ix_check_in_id'), 'check_in', ['id'], unique=False)
    op.create_table('check_in_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('check_in_logs_pkey'))
    )
    op.create_index(op.f('ix_check_in_logs_user_id'), 'check_in_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_check_in_logs_id'), 'check_in_logs', ['id'], unique=False)
    op.create_index(op.f('ix_check_in_logs_event_type'), 'check_in_logs', ['event_type'], unique=False)
    # ### end Alembic commands ###
