"""add exception_emails to form

Revision ID: 78d9dac87570
Revises: d1ca1a1f2b40
Create Date: 2026-01-18 01:32:41.892597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "78d9dac87570"
down_revision: Union[str, Sequence[str], None] = "d1ca1a1f2b40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form",
        sa.Column(
            "exception_emails",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form", "exception_emails")
    # ### end Alembic commands ###
