"""empty message

Revision ID: 9b3428cbb010
Revises: 57a01e6b5c8c
Create Date: 2026-01-25 21:07:18.981716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b3428cbb010'
down_revision: Union[str, Sequence[str], None] = '57a01e6b5c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_in_event_type'), table_name='check_in')
    op.drop_index(op.f('ix_check_in_user_id'), table_name='check_in')
    op.drop_table('check_in')
    op.drop_index(op.f('ix_check_in_logs_event_type'), table_name='check_in_log')
    op.create_index('ix_check_in_event_type', 'check_in_log', ['event_type'], unique=False)
    op.create_index('ix_check_in_user_id', 'check_in_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_check_in_user_id', table_name='check_in_log')
    op.drop_index('ix_check_in_event_type', table_name='check_in_log')
    op.create_index(op.f('ix_check_in_logs_event_type'), 'check_in_log', ['event_type'], unique=False)
    op.create_table('check_in',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('check_in_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('check_in_pkey'))
    )
    op.create_index(op.f('ix_check_in_user_id'), 'check_in', ['user_id'], unique=False)
    op.create_index(op.f('ix_check_in_event_type'), 'check_in', ['event_type'], unique=False)
    # ### end Alembic commands ###
