"""add is_open to form

Revision ID: 9db97cbe2f67
Revises: d62174170d9b
Create Date: 2025-10-19 20:15:24.600502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db97cbe2f67'
down_revision: Union[str, Sequence[str], None] = 'd62174170d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('is_open', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'is_open')
    # ### end Alembic commands ###
