"""create admin_user table and add locking fields to application

Revision ID: c767c615424d
Revises: 9db97cbe2f67
Create Date: 2025-12-12 21:54:11.789680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c767c615424d'
down_revision: Union[str, Sequence[str], None] = '9db97cbe2f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_session_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('application', sa.Column('locked_by', sa.UUID(), nullable=True))
    op.add_column('application', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('decided_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'application', 'user', ['locked_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'application', 'user', ['decided_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_column('application', 'decided_by')
    op.drop_column('application', 'locked_at')
    op.drop_column('application', 'locked_by')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
