"""add decided_at column to application

Revision ID: d1ca1a1f2b40
Revises: c767c615424d
Create Date: 2026-01-07 00:20:21.359946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ca1a1f2b40'
down_revision: Union[str, Sequence[str], None] = 'c767c615424d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('decided_at', sa.DateTime(), nullable=True))

    # Populate decided_at for existing accepted/rejected applications with current timestamp
    op.execute("""
        UPDATE application
        SET decided_at = now()
        WHERE status IN ('ACCEPTED'::applicationstatus, 'REJECTED'::applicationstatus) AND decided_at IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'decided_at')
    # ### end Alembic commands ###
