"""remove question text

Revision ID: 0e9e9b967197
Revises: a0d78e3610ff
Create Date: 2025-09-15 22:56:08.663056

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e9e9b967197"
down_revision: Union[str, Sequence[str], None] = "a0d78e3610ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "question_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question",
        sa.Column("question_text", sa.TEXT(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
