"""generate uuid on default

Revision ID: 8ae814e0479f
Revises: 8e8979c6661b
Create Date: 2025-09-10 22:46:39.214124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ae814e0479f"
down_revision: Union[str, Sequence[str], None] = "8e8979c6661b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("response", "id", server_default=sa.text("gen_random_uuid()"))
    op.alter_column("question", "id", server_default=sa.text("gen_random_uuid()"))
    op.alter_column("user", "id", server_default=sa.text("gen_random_uuid()"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("response", "id", server_default=None)
    op.alter_column("question", "id", server_default=None)
    op.alter_column("user", "id", server_default=None)
    # ### end Alembic commands ###
