"""create application table

Revision ID: 98c0c151e830
Revises: 8ae814e0479f
Create Date: 2025-09-12 03:10:39.613403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98c0c151e830"
down_revision: Union[str, Sequence[str], None] = "8ae814e0479f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("form_key", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="applicationstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["form_key"], ["form.form_key"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("response", sa.Column("application_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "response", "application", ["application_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "response", type_="foreignkey")
    op.drop_column("response", "application_id")
    op.drop_table("application")
    # ### end Alembic commands ###
