"""support file questions and auth0

Revision ID: a0d78e3610ff
Revises: 98c0c151e830
Create Date: 2025-09-12 04:40:49.639484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a0d78e3610ff"
down_revision: Union[str, Sequence[str], None] = "98c0c151e830"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    questiontype_enum = postgresql.ENUM("TEXT", "BOOLEAN", "FILE", name="questiontype")
    questiontype_enum.create(op.get_bind())

    op.add_column(
        "application",
        sa.Column(
            "submission_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("question", sa.Column("question_key", sa.String(), nullable=False))
    op.add_column(
        "question",
        sa.Column(
            "question_type",
            questiontype_enum,
            nullable=False,
        ),
    )
    op.add_column("response", sa.Column("file_s3_key", sa.String(), nullable=True))
    op.add_column("user", sa.Column("auth0_id", sa.String(), nullable=False))
    op.create_unique_constraint(None, "user", ["auth0_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "auth0_id")
    op.drop_column("response", "file_s3_key")
    op.drop_column("question", "question_type")
    op.drop_column("question", "question_key")
    op.drop_column("application", "submission_json")

    # Drop the enum type
    questiontype_enum = postgresql.ENUM("TEXT", "BOOLEAN", "FILE", name="questiontype")
    questiontype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
