"""add new types for questions

Revision ID: f28e4c03a7af
Revises: 0e9e9b967197
Create Date: 2025-09-15 23:03:14.545849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "f28e4c03a7af"
down_revision: Union[str, Sequence[str], None] = "0e9e9b967197"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("response", sa.Column("int_answer", sa.Integer(), nullable=True))
    op.add_column("response", sa.Column("float_answer", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("response", "float_answer")
    op.drop_column("response", "int_answer")
    # ### end Alembic commands ###
