name: Deploy Postgres to EC2

on:
  push:
    branches:
      - master
    paths:
      - 'postgres/docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connect to Tailnet
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy over Tailscale SSH
        env:
          EC2_USER: ec2-user
          EC2_IP: ${{ secrets.DB_EC2_IP }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          PRIVATE_KEY: ${{ secrets.DB_EC2_SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem 

          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << EOF
            cd ~/postgres

            cat > .env <<EOT
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
EOT

            docker-compose pull
            docker-compose up -d
EOF
