name: Run Unit Tests via Pytest

on:
  pull_request:
  push:

jobs:
  build:
    name: Run Unit Tests via Pytest

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Check if tests should run
        id: changes
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          if git diff --name-only origin/${{ github.base_ref }} | grep -E '\.py$|pyproject\.toml|poetry\.lock'; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Test with pytest
        run: |
          poetry run coverage run -m pytest  -v -s

      - name: Generate Coverage Report
        run: |
          poetry run coverage report -m
