name: Run Unit Tests via Pytest

on:
  pull_request:

jobs:
  changes:
    name: Pytest Changes
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - '**.py'
              - 'pyproject.toml'
              - 'poetry.lock'

  tests:
    name: Run Pytest
    needs: changes
    if: needs.changes.outputs.python == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --with dev

      - name: Test with pytest
        run: poetry run coverage run -m pytest -v -s

      - name: Generate Coverage Report
        run: poetry run coverage report -m
